const data = [
  {
    name: "Mark Webber",
    avatar: "./assets/images/avatar-mark-webber.webp",
    action: "reacted to your recent post",
    post: "My first tournament today!",
    group: "",
    message: "",
    picture: "",
    time: "1m ago",
    read: false,
  },
  {
    name: "Angela Gray",
    avatar: "./assets/images/avatar-angela-gray.webp",
    action: "followed you",
    post: "",
    group: "",
    message: "",
    picture: "",
    time: "5m ago",
    read: false,
  },
  {
    name: "Jacob Thompson",
    avatar: "./assets/images/avatar-jacob-thompson.webp",
    action: "has joined your group",
    post: "",
    group: "Chess Club",
    message: "",
    picture: "",
    time: "1 day ago",
    read: false,
  },
  {
    name: "Rizky Hasanuddin",
    avatar: "./assets/images/avatar-rizky-hasanuddin.webp",
    action: "sent you a private message",
    post: "",
    group: "",
    message:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    picture: "",
    time: "5 days ago",
    read: true,
  },
  {
    name: "Kimberly Smith",
    avatar: "./assets/images/avatar-kimberly-smith.webp",
    action: "commented on your picture",
    post: "",
    group: "",
    message: "",
    picture: "./assets/images/image-chess.webp",
    time: "1 week ago",
    read: true,
  },
  {
    name: "Nathan Peterson",
    avatar: "./assets/images/avatar-nathan-peterson.webp",
    action: "reacted to your recent post",
    post: "5 end-game strategies to increase your win rate",
    group: "",
    message: "",
    picture: "",
    time: "2 weeks ago",
    read: true,
  },
  {
    name: "Anna Kim",
    avatar: "./assets/images/avatar-anna-kim.webp",
    action: "left the group",
    post: "",
    group: "Chess Club",
    message: "",
    picture: "",
    time: "2 weeks ago",
    read: true,
  },
];

export default data;
